ililBooks/ilil-books

src/main/java/com/example/ililbooks/domain/book/controller/BookController.java, src/main/java/com/example/ililbooks/domain/book/dto/request/BookCreateRequest.java, src/main/java/com/example/ililbooks/domain/book/dto/request/BookUpdateRequest.java, src/main/java/com/example/ililbooks/domain/book/dto/response/BookResponse.java, src/main/java/com/example/ililbooks/domain/book/entity/Book.java, src/main/java/com/example/ililbooks/domain/book/enums/LimitedType.java, src/main/java/com/example/ililbooks/domain/book/enums/SaleStatus.java, src/main/java/com/example/ililbooks/domain/book/repository/BookRepository.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/global/dto/ValidationMessage.java, src/main/java/com/example/ililbooks/global/dto/response/Response.java, src/main/java/com/example/ililbooks/global/exception/ErrorMessage.java
<br>
- open api, 이미지 추가 및 삭제는 구현하지 않았습니다. 추후 구현 예정입니다. 
- SaleStatus의 판매 중지 Enum명 괜찮은지 확인해 주세요.
- POSTMAN API https://documenter.getpostman.com/view/41325349/2sB2cSi4pA 
<br>
<br>
<br>
<br>
=> [feat] 책 CRUD 구현 

build.gradle, src/main/java/com/example/ililbooks/config/config/SecurityConfig.java, src/main/java/com/example/ililbooks/domain/auth/controller/AuthController.java, src/main/java/com/example/ililbooks/domain/auth/dto/response/AuthAccessTokenResponse.java, src/main/java/com/example/ililbooks/domain/auth/dto/response/AuthTokensResponse.java, src/main/java/com/example/ililbooks/domain/auth/entity/RefreshToken.java, src/main/java/com/example/ililbooks/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/example/ililbooks/domain/auth/service/AuthService.java, src/main/java/com/example/ililbooks/domain/auth/service/TokenService.java, src/main/java/com/example/ililbooks/domain/book/dto/response/BookResponse.java, src/main/java/com/example/ililbooks/domain/book/entity/Book.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/user/controller/UserController.java, src/main/java/com/example/ililbooks/domain/user/dto/request/UserDeleteRequest.java, src/main/java/com/example/ililbooks/domain/user/dto/request/UserUpdatePasswordRequest.java, src/main/java/com/example/ililbooks/domain/user/dto/request/UserUpdateRequest.java, src/main/java/com/example/ililbooks/domain/user/dto/response/UserResponse.java, src/main/java/com/example/ililbooks/domain/user/entity/User.java, src/main/java/com/example/ililbooks/domain/user/entity/Users.java, src/main/java/com/example/ililbooks/domain/user/repository/UserRepository.java, src/main/java/com/example/ililbooks/domain/user/service/UserService.java, src/main/java/com/example/ililbooks/global/dto/ValidationMessage.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthServiceTest.java, src/test/java/com/example/ililbooks/domain/auth/service/TokenServiceTest.java, src/test/java/com/example/ililbooks/domain/user/service/UserServiceTest.java, src/test/java/com/example/ililbooks/domain/user/service/UsersServiceTest.java
=> [feat] redis 적용 및 유저 RUD

src/main/java/com/example/ililbooks/domain/auth/service/AuthService.java, src/main/java/com/example/ililbooks/domain/user/entity/Users.java, src/main/java/com/example/ililbooks/domain/user/service/UserService.java
=> [refactor] 팩토리메서드 of 사용

src/main/java/com/example/ililbooks/domain/book/entity/Book.java, src/main/java/com/example/ililbooks/domain/book/service/BookStokeService.java, src/main/java/com/example/ililbooks/domain/cart/service/CartService.java, src/main/java/com/example/ililbooks/domain/order/controller/OrderController.java, src/main/java/com/example/ililbooks/domain/order/entity/Order.java, src/main/java/com/example/ililbooks/domain/order/repository/OrderRepository.java, src/main/java/com/example/ililbooks/domain/order/service/OrderService.java, src/main/java/com/example/ililbooks/global/exception/ErrorMessage.java
=> [feat] createOrder 작성

src/main/java/com/example/ililbooks/domain/user/service/UserService.java
=> [fix] record 오류 수정

src/main/java/com/example/ililbooks/domain/book/dto/request/BookCreateRequest.java, src/main/java/com/example/ililbooks/domain/book/dto/request/BookUpdateRequest.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/review/dto/request/ReviewCreateRequest.java, src/main/java/com/example/ililbooks/domain/review/dto/request/ReviewUpdateRequest.java, src/main/java/com/example/ililbooks/domain/review/service/ReviewService.java, src/main/java/com/example/ililbooks/domain/user/service/UserService.java, src/main/java/com/example/ililbooks/global/image/dto/request/ImageRequest.java
=> [refactor] RequestDto에 record 적용

src/main/java/com/example/ililbooks/domain/limitedevent/controller/LimitedEventController.java, src/main/java/com/example/ililbooks/domain/limitedreservation/controller/LimitedReservationController.java
=> refactor(limitedEvents): 리뷰 반영 최최종

src/main/java/com/example/ililbooks/domain/book/controller/BookController.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/order/controller/OrderController.java, src/main/java/com/example/ililbooks/domain/order/controller/OrderDeliveryController.java, src/main/java/com/example/ililbooks/domain/order/controller/OrderGetController.java, src/main/java/com/example/ililbooks/domain/order/service/OrderDeliveryService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderGetService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderHistoryService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderService.java
=> [refactor] Pageable 적용

src/main/java/com/example/ililbooks/domain/book/controller/BookController.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/search/controller/BookSearchControllerV1.java, src/main/java/com/example/ililbooks/domain/search/controller/BookSearchControllerV2.java, src/main/java/com/example/ililbooks/domain/search/service/BookSearchService.java
=> refactor(search): Pageable 변경

src/main/java/com/example/ililbooks/client/book/BookClient.java, src/main/java/com/example/ililbooks/domain/book/controller/BookController.java, src/main/java/com/example/ililbooks/domain/book/service/BookOpenApiService.java, src/main/java/com/example/ililbooks/domain/book/service/BookReadService.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/book/service/BookStockService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderService.java, src/main/java/com/example/ililbooks/domain/review/service/ReviewFindService.java
=> [refactor] Service 분리 및 Pageble, webClient 적용

src/main/java/com/example/ililbooks/client/book/BookClient.java, src/main/java/com/example/ililbooks/client/naver/NaverClient.java, src/main/java/com/example/ililbooks/domain/book/controller/BookController.java, src/main/java/com/example/ililbooks/domain/book/service/BookOpenApiService.java, src/main/java/com/example/ililbooks/domain/book/service/BookReadService.java, src/main/java/com/example/ililbooks/domain/book/service/BookService.java, src/main/java/com/example/ililbooks/domain/book/service/BookStockService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderService.java, src/main/java/com/example/ililbooks/domain/review/service/ReviewFindService.java
=> [feat] 네이버 소셜 로그인 webClient 적용

src/main/java/com/example/ililbooks/config/argument/RefreshArgumentResolver.java, src/main/java/com/example/ililbooks/config/config/WebConfig.java, src/main/java/com/example/ililbooks/domain/auth/entity/RefreshToken.java
=> [fix] 토큰 재발급 문제 해결

src/main/java/com/example/ililbooks/domain/auth/service/AuthNaverService.java, src/main/java/com/example/ililbooks/domain/book/dto/response/BookResponse.java, src/main/java/com/example/ililbooks/domain/book/entity/Book.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthNaverServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookReadServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookStockServiceTest.java
=> [test] auth, book 테스트 코드 작성

src/main/java/com/example/ililbooks/domain/auth/service/AuthNaverService.java, src/main/java/com/example/ililbooks/domain/book/dto/response/BookResponse.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthNaverServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookReadServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookServiceTest.java, src/test/java/com/example/ililbooks/domain/book/service/BookStockServiceTest.java, src/test/java/com/example/ililbooks/domain/review/service/ReviewDeleteServiceTest.java, src/test/java/com/example/ililbooks/domain/review/service/ReviewFindServiceTest.java, src/test/java/com/example/ililbooks/domain/review/service/ReviewServiceTest.java
=> [test] 리뷰 테스트 코드 작성

src/main/java/com/example/ililbooks/domain/cart/dto/request/CartItemRequest.java, src/main/java/com/example/ililbooks/domain/cart/dto/request/CartItemUpdateRequest.java, src/main/java/com/example/ililbooks/domain/order/service/OrderHistoryService.java, src/test/java/com/example/ililbooks/domain/cart/service/CartServiceTest.java, src/test/java/com/example/ililbooks/domain/cart/service/CartUpdateServiceTest.java, src/test/java/com/example/ililbooks/domain/order/service/OrderDeliveryServiceTest.java, src/test/java/com/example/ililbooks/domain/order/service/OrderGetServiceTest.java, src/test/java/com/example/ililbooks/domain/order/service/OrderHistoryServiceTest.java, src/test/java/com/example/ililbooks/domain/order/service/OrderServiceTest.java
=> [test] cart, order 테스트 코드 작성

src/main/java/com/example/ililbooks/client/naver/NaverClient.java, src/test/java/com/example/ililbooks/domain/book/service/BookReadServiceTest.java
=> [refactor] test코드 수정 및 소셜 로그인 메서드명 변경

src/main/java/com/example/ililbooks/domain/auth/entity/RefreshToken.java, src/main/java/com/example/ililbooks/domain/auth/service/AuthService.java, src/main/java/com/example/ililbooks/domain/auth/service/TokenService.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthServiceTest.java, src/test/java/com/example/ililbooks/domain/auth/service/TokenServiceTest.java
=> [fix] 토큰 재발급시 저장되지 않는 오류 해결

src/main/java/com/example/ililbooks/domain/user/entity/Users.java
=> [feat] email과 loginType의 복합유니크 설정

src/main/java/com/example/ililbooks/domain/auth/google/service/AuthGoogleService.java, src/main/java/com/example/ililbooks/domain/auth/naver/service/AuthNaverService.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthGoogleServiceTest.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthNaverServiceTest.java
=> [refactor(auth)] 네이버, 구글 로그인 타입 예외 변경

src/main/java/com/example/ililbooks/client/google/GoogleClient.java, src/main/java/com/example/ililbooks/domain/auth/google/service/AuthGoogleService.java, src/main/java/com/example/ililbooks/domain/user/dto/request/UserDeleteRequest.java, src/main/java/com/example/ililbooks/domain/user/entity/Users.java, src/main/java/com/example/ililbooks/domain/user/service/UserService.java, src/test/java/com/example/ililbooks/domain/auth/service/AuthGoogleServiceTest.java, src/test/java/com/example/ililbooks/domain/user/service/UserServiceTest.java
=> [refactor] GoogleClient 리뷰 반영 및 삭제유저 재가입

src/main/java/com/example/ililbooks/domain/auth/controller/AuthController.java, src/test/java/com/example/ililbooks/domain/auth/kakao/service/AuthKakaoServiceTest.java
=> [fix] test 오류 해결 및 간단한 코드 정리

src/main/java/com/example/ililbooks/config/config/AsyncConfig.java, src/main/java/com/example/ililbooks/domain/bestseller/controller/BestSellerController.java, src/main/java/com/example/ililbooks/domain/bestseller/enums/PeriodType.java, src/main/java/com/example/ililbooks/domain/bestseller/service/BestSellerScheduler.java, src/main/java/com/example/ililbooks/domain/bestseller/service/BestSellerService.java, src/main/java/com/example/ililbooks/domain/user/repository/UserRepository.java, src/main/java/com/example/ililbooks/domain/user/service/UserService.java, src/main/java/com/example/ililbooks/global/notification/service/AsyncNotificationService.java, src/main/java/com/example/ililbooks/global/notification/service/NotificationService.java, src/main/resources/application.yml, src/test/java/com/example/ililbooks/domain/order/service/OrderServiceTest.java
메일 300개 전송 
- 비동기 처리 전 요청 소요 시간 : 약 17분
- 비동기 처리 후 요청 소요 시간 : 100 ms 이내
---
=> [feat] 메일 전송 기능 구현, 메일 전송 시 @Async 를 사용한 비동기 처리

src/main/java/com/example/ililbooks/IlilBooksApplication.java, src/main/java/com/example/ililbooks/config/config/SesConfig.java, src/main/java/com/example/ililbooks/domain/book/entity/Book.java, src/main/java/com/example/ililbooks/domain/limitedreservation/entity/LimitedReservation.java, src/main/java/com/example/ililbooks/domain/limitedreservation/enums/LimitedReservationStatus.java, src/main/java/com/example/ililbooks/domain/limitedreservation/repository/LimitedReservationRepository.java, src/main/java/com/example/ililbooks/domain/limitedreservation/service/LimitedReservationReadService.java, src/main/java/com/example/ililbooks/domain/limitedreservation/service/LimitedReservationService.java, src/main/java/com/example/ililbooks/domain/order/service/OrderService.java, src/main/java/com/example/ililbooks/domain/payment/controller/PaymentController.java, src/main/java/com/example/ililbooks/domain/payment/controller/PaymentRestController.java, src/main/java/com/example/ililbooks/domain/payment/dto/request/PaymentOrderRequest.java, src/main/java/com/example/ililbooks/domain/payment/dto/request/PaymentRequest.java, src/main/java/com/example/ililbooks/domain/payment/dto/request/PaymentVerificationRequest.java, src/main/java/com/example/ililbooks/domain/payment/service/PaymentService.java, src/main/java/com/example/ililbooks/global/dto/ValidationMessage.java, src/main/java/com/example/ililbooks/global/exception/ErrorMessage.java, src/test/java/com/example/ililbooks/domain/order/service/OrderFromReservationServiceTest.java, src/test/java/com/example/ililbooks/domain/order/service/OrderServiceTest.java, src/test/java/com/example/ililbooks/domain/payment/service/PaymentServiceTest.java
=> [feat] 예약과 결제 연결

docker-compose.yml, src/main/java/com/example/ililbooks/config/config/SesConfig.java, src/main/resources/application.yml
=> [fix] application.yml 수정

README.md
=> chore: ReadMe 작성

README.md, src/main/java/com/example/ililbooks/client/book/BookClient.java
=> [chore] ReadMe open api 관련 트러블 슈팅 추가

src/main/java/com/example/ililbooks/domain/order/service/OrderService.java, src/main/java/com/example/ililbooks/global/notification/controller/NotificationSesController.java, src/main/java/com/example/ililbooks/global/notification/service/NotificationAsyncService.java, src/main/java/com/example/ililbooks/global/notification/service/NotificationSesService.java, src/test/java/com/example/ililbooks/domain/order/service/OrderServiceTest.java
=> [feat] 주문 알림 rabbitMQ에서 Async로 수정

src/test/java/com/example/ililbooks/domain/limitedreservation/service/LimitedReservationServiceTest.java
=> [test] LimitedReservation 테스트코드 수정
